spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: vagas
  flyway:
    enabled: true
    schemas: vagas
    validate-on-migrate: false
    baseline-on-migrate: true
    baseline-version: 0
    table: vagas_schema_history

  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ''

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

